[config]
version_check = true
fallback_color = "#e82091"
caching = true

[config.wallpaper]
command = "awww"
arguments = ["img", "--transition-type", "random","--transition-fps","144"]
set = true

[templates.btop]
input_path = './templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = "pgrep btop> /dev/null 2>&1 && pkill -12 btop || echo 'no btop'"

[templates.rmpc]
input_path = "./templates/Matugen.ron"
output_path = "~/.config/rmpc/themes/Matugen.ron"

[templates.st]
input_path = './templates/xrdb'
output_path = '~/.local/src/st-kitty/.Xresources'
post_hook = 'xrdb-reload-dwm'

[templates.alacritty]
input_path = './templates/alacritty.toml'
output_path = '~/.config/alacritty/alacritty.toml'

[templates.zathura]
input_path = './templates/zathura-colors'
outputh_path = '~/.config/zathura/zathurarc'

[templates.vexktop]
input_path = './templates/midnight-discord.css'
output_path = '~/.var/app/dev.vencord.Vesktop/config/vesktop/themes/midnight-discord.css'

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/themes/your-theme'
post_hook = "pgrep cava > /dev/null 2>&1 && pkill -10 cava || echo 'no cava'"

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.color-scheme]
input_path = './templates/Matugen.colors'
output_path = '~/.local/share/color-schemes/Matugen.colors'

[templates.mango]
input_path = './templates/mango-colors.conf'
output_path = '~/.config/mango/matugen-colors.conf'
post_hook = 'mmsg -d reload_config'

[templates.yazi]
input_path = './templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.wlogout]
input_path = './templates/colors.css'
output_path = '~/.config/wlogout/colors.css'

[templates.swaync]
input_path = './templates/colors-rgba.css'
output_path = '~/.config/swaync/colors.css'
post_hook= 'swaync-client -rs'
