# yazi.toml

[mgr]
show_hidden=true
sort_by="natural"
sort_dir_first=true
sort_translit=false
linemode="none"
show_symlink=true

[preview]
wrap="no"
max_width=600
max_height=600
image_delay=100
image_filter="catmull-rom"
image_quality=75
ueberzug_scale=0.5
image_alloc=24000000
image_bound=[]

[task]
micro_workers=5
macro_workers=1
bizarre_retry=3
image_alloc=24000000
image_bound=[600, 600]
